[package]
name = "rustfire"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
minifier = "0.2.2"
libflate = "1.2.0"
clipboard = "0.5.0"